const menu = [
    {
    id: 1,
    title: 'Fresh Rolls',
    category: 'Appetizers',
    price: 7.99,
    img: './images/freshRolls2.jpg',
    desc: `Fresh lettuce, basil, carrot, avocado wrapped in rice skin and served with home made sauce`,
  },
  {
    id: 2,
    title: 'Miang Kham',
    category: 'Appetizers',
    price: 7.99,
    img: './images/miang-kham.jpg',
    desc: `Leaf-wrapped salad bites. Each wrap is filled with ginger, chillies, peanuts, lime, dried coconut and dried shrimp `,
  },
  {
    id: 3,
    title: 'Som Tum',
    category: 'Appetizers',
    price: 6.99,
    img: './images/somTum.jpg',
    desc: `Sliced green papaya, carrot, cashew nut, crashed peanut in spicy lime juice `,
  },
  {
    id: 4,
    title: 'Pad Thai',
    category: 'Noodles',
    price: 15.99,
    img: './images/padThai.jpg',
    desc: `Famous Thai rice noodle dish, stir fried with, bean sprouts, scallion, egg and crush peanuts`,
  },
  {
    id: 5,
    title: 'Drunken Noodle',
    category: 'Noodles',
    price: 15.99,
    img: './images/drunkenNoodles.jpg',
    desc: `Stir fried wide noodle with bell pepper, bamboo, string beans, carrot, broccoli, tomato & basil`,
  },
  {
    id: 6,
    title: 'Tom Yum Noodle soup',
    category: 'Noodles',
    price: 15.99,
    img: './images/tomYum.jpg',
    desc: `Spicy, sweet & sour in clear broth rice noodle soup with ground peanut, broccoli, and chopped cilantro & scallion`,
  },
  {
    id: 7,
    title: 'Larb',
    category: 'Entree',
    price: 15.99,
    img: './images/larb.jpg',
    desc: `Finely chopped firm tofu, mushroom, with Thai chili pepper, frest mint, lemongrass, lime juice and fish sauce.`,
  },
  {
    id: 8,
    title: 'Pumpkin Curry',
    category: 'Entree',
    price: 15.99,
    img: './images/pumpkinCurry.jpg',
    desc: `Slow cooked in coconut milk with soy-meat, potato, sweet potato, bell pepper, pumpkin, basil in red curry`,
  },
  {
    id: 9,
    title: 'Avocado Green Curry',
    category: 'Entree',
    price: 17.99,
    img: './images/avoGreenCurry.jpg',
    desc: `Slow cooked in coconut milk with soy-meat, string beans, eggplant, green peas, zucchini, bell peppers, basil and avocado in green curry `,
  },
  {
    id: 10,
    title: 'Fried Rice',
    category: 'Entree',
    price: 10.99,
    img: './images/friedRice.jpg',
    desc: 'Jasmine brown rice stir-fried with soy-meat, onions, tomatoes, bell peppers, Thai basil, Chinese broccoli, and egg',
  }
]
export default menu